[features]
seeds = false
skip-lint = false
[programs.localnet]
loader = "GDfgxSRyoQYdNN7vTJRr82N6Jqg11v6oTwYTjguZ7yuJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/wuhao/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
